"""Write the BE Flyway migrations V2__mountains.sql (mountains.csv + mountain_descriptions.csv)
and V3__courses.sql (courses.geojson).

Usage: python scripts/build_seed_sql.py <path to BE/src/main/resources/db/migration>
"""
import csv
import json
import math
import sys
from pathlib import Path

DATA = Path(__file__).resolve().parent.parent / 'data'

# Same grouping as FE src/data/exploreRegions.ts.
REGIONS = {
    'SOUTH': '용인시 평택시 이천시 안성시 여주시',
    'EAST': '성남시 남양주시 광주시 하남시 구리시 양평군 가평군',
    'NORTH': '고양시 의정부시 파주시 김포시 양주시 포천시 동두천시 연천군',
    'CENTRAL': '수원시 부천시 안산시 화성시 안양시 시흥시 광명시 군포시 오산시 의왕시 과천시',
}
REGION_OF = {city: region for region, cities in REGIONS.items() for city in cities.split()}

# 행정표준 시군구 코드. The CSV's sigungu_code comes from forest codes and is wrong for border mountains.
SIGUNGU_CODE = {
    '수원시': '41110', '성남시': '41130', '의정부시': '41150', '안양시': '41170', '부천시': '41190',
    '광명시': '41210', '평택시': '41220', '동두천시': '41250', '안산시': '41270', '고양시': '41280',
    '과천시': '41290', '구리시': '41310', '남양주시': '41360', '오산시': '41370', '시흥시': '41390',
    '군포시': '41410', '의왕시': '41430', '하남시': '41450', '용인시': '41460', '파주시': '41480',
    '이천시': '41500', '안성시': '41550', '김포시': '41570', '화성시': '41590', '광주시': '41610',
    '양주시': '41630', '포천시': '41650', '여주시': '41670', '연천군': '41800', '가평군': '41820',
    '양평군': '41830',
}

# Mountains shown under a different Gyeonggi city than the CSV says (Seoul border mountains, 수리산).
CITY_OVERRIDE = {
    '북한산': '고양시', '관악산': '과천시',
    '아차산': '구리시', '구릉산': '구리시', '망우산': '구리시', '용마산 (경기)': '구리시',
    '수락산': '남양주시', '불암산': '남양주시', '수리산': '군포시',
}


def kma_grid(lat, lon):
    """KMA 단기예보 grid (Lambert conformal conic, 5 km)."""
    re_, grid, slat1, slat2, olon, olat, xo, yo = 6371.00877, 5.0, 30.0, 60.0, 126.0, 38.0, 43, 136
    d = math.pi / 180
    re_ /= grid
    slat1, slat2, olon, olat = slat1 * d, slat2 * d, olon * d, olat * d
    sn = math.log(math.cos(slat1) / math.cos(slat2)) / math.log(
        math.tan(math.pi / 4 + slat2 / 2) / math.tan(math.pi / 4 + slat1 / 2))
    sf = math.tan(math.pi / 4 + slat1 / 2) ** sn * math.cos(slat1) / sn
    ro = re_ * sf / math.tan(math.pi / 4 + olat / 2) ** sn
    ra = re_ * sf / math.tan(math.pi / 4 + lat * d / 2) ** sn
    theta = lon * d - olon
    theta = (theta + math.pi) % (2 * math.pi) - math.pi
    theta *= sn
    return math.floor(ra * math.sin(theta) + xo + 0.5), math.floor(ro - ra * math.cos(theta) + yo + 0.5)


def q(v):
    return 'NULL' if v in (None, '') else "'" + v.replace("'", "''") + "'"


def main(out_dir):
    assert kma_grid(37.5665, 126.9780) == (60, 127)  # 서울시청, KMA reference value
    rows = list(csv.DictReader(open(DATA / 'mountains.csv', encoding='utf-8-sig')))
    desc = {r['name']: r['description'] for r in csv.DictReader(open(DATA / 'mountain_descriptions.csv', encoding='utf-8-sig'))}
    assert SIGUNGU_CODE.keys() == REGION_OF.keys()
    ids = [int(r['id']) for r in rows]
    assert len(set(ids)) == len(ids), 'duplicate id in mountains.csv'

    values = []
    for r in rows:
        city = CITY_OVERRIDE.get(r['name'], r['sigungu_name'])
        sigungu_code = SIGUNGU_CODE[city]
        lat, lng = float(r['summit_lat']), float(r['summit_lon'])
        nx, ny = kma_grid(lat, lng)
        address = ' '.join(r['address'].split())
        values.append(f"({int(r['id'])}, {q(r['name'])}, '{REGION_OF[city]}', '{sigungu_code}', {q(city)}, {q(address)}, "
                      f"{float(r['height']):.1f}, {lat}, {lng}, {nx}, {ny}, {q(desc[r['name']])})")

    sql = f"""CREATE TABLE mountains (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(30) NOT NULL UNIQUE,
 region VARCHAR(10) NOT NULL CHECK (region IN ('NORTH','EAST','CENTRAL','SOUTH')),
 sigungu_code VARCHAR(5) NOT NULL,
 sigungu_name VARCHAR(20) NOT NULL,
 address VARCHAR(100) NOT NULL,
 height DOUBLE PRECISION NOT NULL,
 lat DOUBLE PRECISION NOT NULL,
 lng DOUBLE PRECISION NOT NULL,
 grid_nx INTEGER NOT NULL,
 grid_ny INTEGER NOT NULL,
 description VARCHAR(300)
);
CREATE INDEX mountains_region_sigungu ON mountains(region, sigungu_name);

-- {len(values)} mountains. Generated by hiking/scripts/build_seed_sql.py; edit the CSVs, not this file.
-- Sources: 산림청 산정보 API / 등산로 data, OpenStreetMap (ODbL) summit coordinates.
INSERT INTO mountains (id, name, region, sigungu_code, sigungu_name, address, height, lat, lng, grid_nx, grid_ny, description) VALUES
""" + ',\n'.join(values) + f""";

-- ids come from the CSV (stable, referenced by courses); continue the sequence after them.
ALTER TABLE mountains ALTER COLUMN id RESTART WITH {max(ids) + 1};
"""
    out = Path(out_dir) / 'V2__mountains.sql'
    out.write_text(sql, encoding='utf-8', newline='\n')
    print(f'{out}: {len(values)} rows')
    write_courses(out_dir)


DIFFICULTY = {'쉬움': 'EASY', '보통': 'NORMAL', '어려움': 'HARD'}
SIMPLIFY_M = 2.0  # map lines: dropping points within 2 m of the line cuts 440k points to ~60k


def simplify(coords, tol=SIMPLIFY_M):
    """Douglas-Peucker on [lng, lat] (local metres), keeping original coordinates."""
    kx = 111320 * math.cos(math.radians(coords[0][1]))
    pts = [(lng * kx, lat * 110540) for lng, lat in coords]
    keep, stack = {0, len(pts) - 1}, [(0, len(pts) - 1)]
    while stack:
        a, b = stack.pop()
        (x1, y1), (x2, y2) = pts[a], pts[b]
        seg = math.hypot(x2 - x1, y2 - y1) or 1e-9
        far, worst = None, tol
        for k in range(a + 1, b):
            d = abs((x2 - x1) * (y1 - pts[k][1]) - (x1 - pts[k][0]) * (y2 - y1)) / seg
            if d > worst:
                far, worst = k, d
        if far is not None:
            keep.add(far)
            stack += [(a, far), (far, b)]
    return [[round(coords[i][0], 6), round(coords[i][1], 6)] for i in sorted(keep)]


def write_courses(out_dir):
    feats = json.load(open(DATA / 'courses.geojson', encoding='utf-8'))['features']
    n_in = n_out = 0
    values = []
    for f in feats:
        p, coords = f['properties'], f['geometry']['coordinates']
        path = simplify(coords)
        n_in, n_out = n_in + len(coords), n_out + len(path)
        num = lambda v: 'NULL' if v in ('', None) else str(v)
        values.append(f"({int(p['mountain_id'])}, '{p['source'].upper()}', {q(p['name'])}, {q(p['start_name'])}, {p['start_lat']}, {p['start_lon']}, "
                      f"{num(p['start_elev_m'])}, {num(p['climb_m'])}, {p['length_km']}, {p['up_min']}, {p['down_min']}, "
                      f"'{DIFFICULTY[p['difficulty']]}', {q(p['risk'])}, {q(json.dumps(path, separators=(',', ':')))})")
    sql = f"""CREATE TABLE courses (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 mountain_id BIGINT NOT NULL REFERENCES mountains(id),
 source VARCHAR(10) NOT NULL CHECK (source IN ('FOREST','OSM')),
 name VARCHAR(50) NOT NULL,
 start_name VARCHAR(30) NOT NULL,
 start_lat DOUBLE PRECISION NOT NULL,
 start_lng DOUBLE PRECISION NOT NULL,
 start_elevation INTEGER,
 climb INTEGER,
 length_km DOUBLE PRECISION NOT NULL,
 up_min INTEGER NOT NULL,
 down_min INTEGER NOT NULL,
 difficulty VARCHAR(10) NOT NULL CHECK (difficulty IN ('EASY','NORMAL','HARD')),
 risk VARCHAR(100),
 path TEXT NOT NULL,
 UNIQUE (mountain_id, name)
);
CREATE INDEX courses_mountain ON courses(mountain_id);

-- {len(values)} courses (trailhead -> summit, one way). Generated by hiking/scripts/build_seed_sql.py from data/courses.geojson.
-- Plain INTEGER / DOUBLE PRECISION / VARCHAR so JPA Integer / Double / String fields pass ddl-auto=validate.
-- start_elevation, climb: metres. length_km: one way. up_min / down_min: minutes.
-- path: JSON array of [lng, lat] (GeoJSON LineString coordinates), simplified to {SIMPLIFY_M:g} m.
-- Sources: FOREST = 산림빅데이터거래소 (c) 시선아이티 CC BY + 산림청 등산로; OSM = (c) OpenStreetMap contributors, ODbL.
-- start_elev_m: Copernicus DEM via Open-Meteo.
INSERT INTO courses (mountain_id, source, name, start_name, start_lat, start_lng, start_elevation, climb, length_km, up_min, down_min, difficulty, risk, path) VALUES
""" + ',\n'.join(values) + ';\n'
    out = Path(out_dir) / 'V3__courses.sql'
    out.write_text(sql, encoding='utf-8', newline='\n')
    print(f'{out}: {len(values)} rows, path points {n_in} -> {n_out}')


if __name__ == '__main__':
    main(sys.argv[1])
